-- +goose Up
-- +goose StatementBegin
CREATE TABLE customers (
    ID INT PRIMARY KEY,
    CustomerID INT,
    FullName VARCHAR(255),
    CompanyName VARCHAR(255),
    CompanyTypeID INT,
    FirstName VARCHAR(255),
    LastName VARCHAR(255),
    PersonTitleID INT,
    EInvoiceEmail VARCHAR(255),
    EInvoiceReference VARCHAR(255),
    EmailEnabled INT,
    EInvoiceEnabled INT,
    DocuraEDIEnabled INT,
    MailEnabled INT,
    OperatorIdentifier VARCHAR(255),
    EDI VARCHAR(255),
    DoNotSell INT,
    PartialTaxExemption INT,
    GroupID INT,
    CountryID VARCHAR(255),
    PayerID INT,
    Phone VARCHAR(255),
    Mobile VARCHAR(255),
    Email VARCHAR(255),
    Fax VARCHAR(255),
    Code VARCHAR(255),
    Birthday VARCHAR(255),
    IntegrationCode VARCHAR(255),
    FlagStatus INT,
    ColorStatus VARCHAR(255),
    Credit INT,
    SalesBlocked INT,
    ReferenceNumber VARCHAR(255),
    CustomerCardNumber VARCHAR(255),
    FactoringContractNumber VARCHAR(255),
    GroupName VARCHAR(255),
    CustomerType VARCHAR(255),
    Address VARCHAR(255),
    Street VARCHAR(255),
    Address2 VARCHAR(255),
    City VARCHAR(255),
    PostalCode VARCHAR(255),
    Country VARCHAR(255),
    State VARCHAR(255),
    AddressTypeID INT,
    AddressTypeName VARCHAR(255),
    IsPOSDefaultCustomer INT,
    EUCustomerType VARCHAR(255),
    EDIType VARCHAR(255),
    LastModifierUsername VARCHAR(255),
    LastModifierEmployeeID INT,
    TaxExempt INT,
    PaysViaFactoring INT,
    RewardPoints INT,
    TwitterID VARCHAR(255),
    FacebookName VARCHAR(255),
    CreditCardLastNumbers VARCHAR(255),
    GLN VARCHAR(255),
    DeliveryTypeID INT,
    Image VARCHAR(255),
    CustomerBalanceDisabled INT,
    RewardPointsDisabled INT,
    PosCouponsDisabled INT,
    EmailOptOut INT,
    SignUpStoreID INT,
    HomeStoreID INT,
    Gender VARCHAR(255),
    PeppolID VARCHAR(255),
    ExternalIDs JSON
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
-- +goose StatementEnd
